name: CD - main branch

on:
  push:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
    
    - name: Build app
      run: npm run build
      
    - name: Copy build to host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        rm: true
        source: './'
        target: '~/github/${{ github.event.repository.name }}'  
        strip_components: 1
    
    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: 'cd ~/github/${{ github.event.repository.name }} && npx prisma generate && cd ../ && sh deploy.sh ${{ github.event.repository.name }} '
